/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildErrorsPanel: typeof import('./src/components/BuildErrorsPanel.vue')['default']
    BuildStatusPanel: typeof import('./src/components/BuildStatusPanel.vue')['default']
    MediaVirtualGrid: typeof import('./src/components/MediaVirtualGrid.vue')['default']
    SearchToolbar: typeof import('./src/components/SearchToolbar.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UProgress: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USkeleton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
